CC Steer: smt/cc-dubins.h File Reference
smt/cc-dubins.h File Reference
#include <iostream>
#include <float.h>
#include <utilities.h>
#include <configuration.h>
#include <paths.h>
Functions
SMT_CC_Dubins_Path * cc_dubins (SMT_Configuration start, SMT_Configuration end, double kappa, double sigma)
Function Documentation
SMT_CC_Dubins_Path* cc_dubins (SMT_Configuration start, SMT_Configuration end, double kappa, double sigma)
Definition at line 14 of file cc-dubins.cc.
References array_index_min(), configuration_aligned(), configuration_distance(), configuration_equal(), configuration_on_cc_circle(), double_array_init(), dubins_turn_length(), EMPTY, external_mu_tangent(), external_mu_tangent_exists(), internal_mu_tangent(), internal_mu_tangent_exists(), L, look_at_chronometer(), LR1L, LR2L, LS, LSL, LSR, nb_cc_dubins_paths, pointer_array_init(), R, RL1R, RL2R, RS, RSL, RSR, S, SL, SR, start_chronometer(), tangent_circle(), and tangent_circle_exists().
Referenced by cb_dubins_rs(), and main().