CC Steer: smt/cc-rs.cc File Reference
smt/cc-rs.cc File Reference
#include <cc-rs.h>
Functions
bool TT_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
double TT_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q)
bool TcT_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
double TcT_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q)
bool TiST_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
bool TeST_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
bool TST_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
double TiST_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2)
double TeST_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2)
double TST_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2)
bool TciST_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
bool TceST_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
bool TcST_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
double TciST_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2)
double TceST_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2)
double TcST_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2)
bool TiScT_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
bool TeScT_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
bool TScT_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
double TiScT_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2)
double TeScT_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2)
double TScT_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2)
bool TciScT_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
bool TceScT_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
bool TcScT_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
double TciScT_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2)
double TceScT_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2)
double TcScT_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2)
void TTT_tangent_circles (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2, SMT_Configuration **q3, SMT_Configuration **q4)
bool TTT_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
double TTT_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2, SMT_CC_Circle **ci)
void TcTT_tangent_circles (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2, SMT_Configuration **q3, SMT_Configuration **q4)
bool TcTT_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
double TcTT_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2, SMT_CC_Circle **ci)
void TTcT_tangent_circles (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2, SMT_Configuration **q3, SMT_Configuration **q4)
bool TTcT_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
double TTcT_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2, SMT_CC_Circle **ci)
void TcTcT_tangent_circles (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2, SMT_Configuration **q3, SMT_Configuration **q4)
bool TcTcT_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
double TcTcT_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2, SMT_CC_Circle **ci)
bool TTiSTT_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
bool TTeSTT_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
bool TTSTT_exists (SMT_CC_Circle *c1, SMT_CC_Circle *c2)
double TTSTT_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, SMT_Configuration **q1, SMT_Configuration **q2, SMT_Configuration **q3, SMT_Configuration **q4, SMT_CC_Circle **ci1, SMT_CC_Circle **ci2)
SMT_CC_RS_Path * cc_circles_rs_path (SMT_CC_Circle *c1, SMT_CC_Circle *c2, double kappa, double sigma)
SMT_CC_RS_Path * cc_reeds_shepp (SMT_Configuration start, SMT_Configuration end, double kappa, double sigma)
Function Documentation
SMT_CC_RS_Path* cc_circles_rs_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, double kappa, double sigma)
Definition at line 932 of file cc-rs.cc.
References array_index_min(), configuration_aligned(), configuration_distance(), configuration_equal(), configuration_on_cc_circle(), double_array_init(), Empty, nb_cc_rs_paths, pointer_array_init(), rs_turn_length(), Segment, SMT_CC_Circle::start, T, TcScT, TcScT_exists(), TcScT_path(), TcST, TcST_exists(), TcST_path(), TcT, TcT_exists(), TcT_path(), TcTcT, TcTcT_exists(), TcTcT_path(), TcTT, TcTT_exists(), TcTT_path(), TScT, TScT_exists(), TScT_path(), TST, TST_exists(), TST_path(), TT, TT_exists(), TT_path(), TTcT, TTcT_exists(), TTcT_path(), TTT, TTT_exists(), and TTT_path().
Referenced by cc_reeds_shepp().
SMT_CC_RS_Path* cc_reeds_shepp (SMT_Configuration start, SMT_Configuration end, double kappa, double sigma)
Definition at line 1082 of file cc-rs.cc.
References array_index_min(), cc_circles_rs_path(), SMT_Path::length, look_at_chronometer(), null(), start_chronometer(), and SMT_Path::time.
Referenced by cb_dubins_rs(), and main().
bool TceScT_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 474 of file cc-rs.cc.
References SMT_CC_Circle::forward, get_epsilon(), SMT_CC_Circle::left, point_distance(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TcScT_exists(), and TcScT_path().
double TceScT_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2)
Definition at line 536 of file cc-rs.cc.
References configuration_distance(), SMT_CC_Circle::forward, global_frame_change(), SMT_CC_Circle::left, SMT_CC_Circle::mu, Pi, SMT_CC_Circle::radius, rs_turn_length(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TcScT_path().
bool TceST_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 232 of file cc-rs.cc.
References SMT_CC_Circle::forward, get_epsilon(), SMT_CC_Circle::left, point_distance(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TcST_exists(), and TcST_path().
double TceST_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2)
Definition at line 294 of file cc-rs.cc.
References configuration_distance(), SMT_CC_Circle::forward, global_frame_change(), SMT_CC_Circle::left, SMT_CC_Circle::mu, Pi, SMT_CC_Circle::radius, rs_turn_length(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TcST_path().
bool TciScT_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 465 of file cc-rs.cc.
References SMT_CC_Circle::forward, SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TcScT_exists(), and TcScT_path().
double TciScT_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2)
Definition at line 487 of file cc-rs.cc.
References configuration_distance(), SMT_CC_Circle::forward, global_frame_change(), SMT_CC_Circle::left, SMT_CC_Circle::mu, Pi, point_distance(), SMT_CC_Circle::radius, rs_turn_length(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TcScT_path().
bool TciST_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 223 of file cc-rs.cc.
References SMT_CC_Circle::forward, SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TcST_exists(), and TcST_path().
double TciST_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2)
Definition at line 245 of file cc-rs.cc.
References configuration_distance(), SMT_CC_Circle::forward, global_frame_change(), SMT_CC_Circle::left, SMT_CC_Circle::mu, Pi, point_distance(), SMT_CC_Circle::radius, rs_turn_length(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TcST_path().
bool TcScT_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 483 of file cc-rs.cc.
References TceScT_exists(), and TciScT_exists().
Referenced by cc_circles_rs_path().
double TcScT_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2)
Definition at line 577 of file cc-rs.cc.
References TceScT_exists(), TceScT_path(), TciScT_exists(), and TciScT_path().
Referenced by cc_circles_rs_path().
bool TcST_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 241 of file cc-rs.cc.
References TceST_exists(), and TciST_exists().
Referenced by cc_circles_rs_path().
double TcST_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2)
Definition at line 335 of file cc-rs.cc.
References TceST_exists(), TceST_path(), TciST_exists(), and TciST_path().
Referenced by cc_circles_rs_path().
bool TcT_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 54 of file cc-rs.cc.
References SMT_CC_Circle::forward, get_epsilon(), SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by cc_circles_rs_path().
double TcT_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q)
Definition at line 65 of file cc-rs.cc.
References SMT_CC_Circle::forward, global_frame_change(), Half_Pi, SMT_CC_Circle::left, point_distance(), SMT_CC_Circle::radius, rs_turn_length(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by cc_circles_rs_path(), TcTcT_tangent_circles(), TcTT_tangent_circles(), and TTcT_tangent_circles().
bool TcTcT_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 828 of file cc-rs.cc.
References SMT_CC_Circle::forward, SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by cc_circles_rs_path().
double TcTcT_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2, SMT_CC_Circle ** ci)
Definition at line 837 of file cc-rs.cc.
References SMT_CC_Circle::forward, SMT_CC_Circle::kappa, SMT_CC_Circle::left, rs_turn_length(), SMT_CC_Circle::sigma, and TcTcT_tangent_circles().
Referenced by cc_circles_rs_path().
void TcTcT_tangent_circles (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2, SMT_Configuration ** q3, SMT_Configuration ** q4)
Definition at line 800 of file cc-rs.cc.
References SMT_CC_Circle::forward, global_frame_change(), SMT_CC_Circle::kappa, SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::sigma, TcT_path(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TcTcT_path().
bool TcTT_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 686 of file cc-rs.cc.
References SMT_CC_Circle::forward, SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by cc_circles_rs_path().
double TcTT_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2, SMT_CC_Circle ** ci)
Definition at line 695 of file cc-rs.cc.
References SMT_CC_Circle::forward, SMT_CC_Circle::kappa, SMT_CC_Circle::left, rs_turn_length(), SMT_CC_Circle::sigma, and TcTT_tangent_circles().
Referenced by cc_circles_rs_path().
void TcTT_tangent_circles (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2, SMT_Configuration ** q3, SMT_Configuration ** q4)
Definition at line 656 of file cc-rs.cc.
References SMT_CC_Circle::forward, global_frame_change(), SMT_CC_Circle::kappa, SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::sigma, TcT_path(), TT_path(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TcTT_path().
bool TeScT_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 353 of file cc-rs.cc.
References SMT_CC_Circle::forward, get_epsilon(), SMT_CC_Circle::left, point_distance(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TScT_exists(), and TScT_path().
double TeScT_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2)
Definition at line 415 of file cc-rs.cc.
References configuration_distance(), SMT_CC_Circle::forward, global_frame_change(), SMT_CC_Circle::left, SMT_CC_Circle::mu, Pi, SMT_CC_Circle::radius, rs_turn_length(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TScT_path().
bool TeST_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 111 of file cc-rs.cc.
References SMT_CC_Circle::forward, SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TST_exists(), and TST_path().
double TeST_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2)
Definition at line 173 of file cc-rs.cc.
References configuration_distance(), SMT_CC_Circle::forward, global_frame_change(), SMT_CC_Circle::left, SMT_CC_Circle::mu, Pi, SMT_CC_Circle::radius, rs_turn_length(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TST_path().
bool TiScT_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 344 of file cc-rs.cc.
References SMT_CC_Circle::forward, SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TScT_exists(), and TScT_path().
double TiScT_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2)
Definition at line 366 of file cc-rs.cc.
References configuration_distance(), SMT_CC_Circle::forward, global_frame_change(), SMT_CC_Circle::left, SMT_CC_Circle::mu, Pi, point_distance(), SMT_CC_Circle::radius, rs_turn_length(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TScT_path().
bool TiST_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 102 of file cc-rs.cc.
References SMT_CC_Circle::forward, SMT_CC_Circle::left, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TST_exists(), and TST_path().
double TiST_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2)
Definition at line 124 of file cc-rs.cc.
References configuration_distance(), SMT_CC_Circle::forward, global_frame_change(), SMT_CC_Circle::left, SMT_CC_Circle::mu, Pi, point_distance(), SMT_CC_Circle::radius, rs_turn_length(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TST_path().
bool TScT_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 362 of file cc-rs.cc.
References TeScT_exists(), and TiScT_exists().
Referenced by cc_circles_rs_path().
double TScT_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2)
Definition at line 456 of file cc-rs.cc.
References TeScT_exists(), TeScT_path(), TiScT_exists(), and TiScT_path().
Referenced by cc_circles_rs_path().
bool TST_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 120 of file cc-rs.cc.
References TeST_exists(), and TiST_exists().
Referenced by cc_circles_rs_path().
double TST_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2)
Definition at line 214 of file cc-rs.cc.
References TeST_exists(), TeST_path(), TiST_exists(), and TiST_path().
Referenced by cc_circles_rs_path().
bool TT_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 21 of file cc-rs.cc.
References SMT_CC_Circle::forward, get_epsilon(), SMT_CC_Circle::left, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by cc_circles_rs_path().
double TT_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q)
Definition at line 31 of file cc-rs.cc.
References SMT_CC_Circle::forward, Half_Pi, SMT_CC_Circle::left, SMT_CC_Circle::mu, rs_turn_length(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by cc_circles_rs_path(), TcTT_tangent_circles(), TTcT_tangent_circles(), and TTT_tangent_circles().
bool TTcT_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 758 of file cc-rs.cc.
References SMT_CC_Circle::forward, SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by cc_circles_rs_path().
double TTcT_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2, SMT_CC_Circle ** ci)
Definition at line 767 of file cc-rs.cc.
References SMT_CC_Circle::forward, SMT_CC_Circle::kappa, SMT_CC_Circle::left, rs_turn_length(), SMT_CC_Circle::sigma, and TTcT_tangent_circles().
Referenced by cc_circles_rs_path().
void TTcT_tangent_circles (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2, SMT_Configuration ** q3, SMT_Configuration ** q4)
Definition at line 728 of file cc-rs.cc.
References SMT_CC_Circle::forward, global_frame_change(), SMT_CC_Circle::kappa, SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::sigma, TcT_path(), TT_path(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TTcT_path().
bool TTeSTT_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 908 of file cc-rs.cc.
References SMT_CC_Circle::forward, get_epsilon(), SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TTSTT_exists().
bool TTiSTT_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 898 of file cc-rs.cc.
References SMT_CC_Circle::forward, get_epsilon(), SMT_CC_Circle::left, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TTSTT_exists().
bool TTSTT_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 920 of file cc-rs.cc.
References TTeSTT_exists(), and TTiSTT_exists().
double TTSTT_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2, SMT_Configuration ** q3, SMT_Configuration ** q4, SMT_CC_Circle ** ci1, SMT_CC_Circle ** ci2)
Definition at line 924 of file cc-rs.cc.
bool TTT_exists (SMT_CC_Circle * c1, SMT_CC_Circle * c2)
Definition at line 614 of file cc-rs.cc.
References SMT_CC_Circle::forward, SMT_CC_Circle::left, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by cc_circles_rs_path().
double TTT_path (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2, SMT_CC_Circle ** ci)
Definition at line 623 of file cc-rs.cc.
References SMT_CC_Circle::forward, SMT_CC_Circle::kappa, SMT_CC_Circle::left, rs_turn_length(), SMT_CC_Circle::sigma, and TTT_tangent_circles().
Referenced by cc_circles_rs_path().
void TTT_tangent_circles (SMT_CC_Circle * c1, SMT_CC_Circle * c2, SMT_Configuration ** q1, SMT_Configuration ** q2, SMT_Configuration ** q3, SMT_Configuration ** q4)
Definition at line 586 of file cc-rs.cc.
References SMT_CC_Circle::forward, global_frame_change(), SMT_CC_Circle::kappa, SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::sigma, TT_path(), SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by TTT_path().