CC Steer: FLTK_Plus Class Reference
FLTK_Plus Class Reference
#include <graphic-objects.h>
Public Member Functions
FLTK_Plus (double _x=0.0, double _y=0.0, double _size=0.0, Fl_Color _color=FL_BLACK, int _style=FL_SOLID, int _width=0)
void draw (FLTK_Display *display)
void print ()
void xfigicize (ofstream &output)
Public Attributes
double x
double y
double size
Detailed Description
Classe FLTK_Plus: objet graphique de type plus destiné à être affiché dans un widget FLTK_Display_control.
Definition at line 131 of file graphic-objects.h.
Constructor & Destructor Documentation
FLTK_Plus::FLTK_Plus (double _x = 0.0, double _y = 0.0, double _size = 0.0, Fl_Color _color = FL_BLACK, int _style = FL_SOLID, int _width = 0)
Constructeur.
Parameters:
_x abcisse du centre du plus (repère "monde").
_y ordonnée du centre du plus (repère "monde").
_size longueur d'une demi-branche du plus (repère "monde").
_color couleur du point.
_style style du point.
_width épaisseur du trait.
Definition at line 150 of file graphic-objects.cc.
References size, x, and y.
Member Function Documentation
void FLTK_Plus::draw (FLTK_Display * display) [virtual]
Implements FLTK_Graphic_Object.
Definition at line 156 of file graphic-objects.cc.
References FLTK_Graphic_Object::color, FLTK_Display::get_scroll_x(), FLTK_Display::get_scroll_y(), FLTK_Display::get_unit_size(), size, FLTK_Graphic_Object::style, FLTK_Graphic_Object::width, world_to_display_x(), world_to_display_y(), x, and y.
void FLTK_Plus::print () [virtual]
Implements FLTK_Graphic_Object.
Definition at line 176 of file graphic-objects.cc.
References size, x, and y.
void FLTK_Plus::xfigicize (ofstream & output) [virtual]
Implements FLTK_Graphic_Object.
Definition at line 180 of file graphic-objects.cc.
References FLTK_Graphic_Object::color, size, FLTK_Graphic_Object::style, FLTK_Graphic_Object::width, x, xfig_parametres(), xfig_x(), xfig_y(), and y.
Member Data Documentation
double FLTK_Plus::x
Definition at line 134 of file graphic-objects.h.
Referenced by draw(), FLTK_Plus(), print(), and xfigicize().
double FLTK_Plus::y
Definition at line 134 of file graphic-objects.h.
Referenced by draw(), FLTK_Plus(), print(), and xfigicize().
double FLTK_Plus::size
Definition at line 134 of file graphic-objects.h.
Referenced by draw(), FLTK_Plus(), print(), and xfigicize().
The documentation for this class was generated from the following files:
fltk-graphics/graphic-objects.h
fltk-graphics/graphic-objects.cc