CC Steer: FLTK_Point Class Reference
FLTK_Point Class Reference
#include <graphic-objects.h>
Public Member Functions
FLTK_Point (double _x=0.0, double _y=0.0, Fl_Color _color=FL_BLACK, int _width=0)
void draw (FLTK_Display *display)
void print ()
void xfigicize (ofstream &output)
Public Attributes
double x
double y
Detailed Description
Classe FLTK_Point: objet graphique de type point destiné à être affiché dans un widget FLTK_Display_control.
Definition at line 76 of file graphic-objects.h.
Constructor & Destructor Documentation
FLTK_Point::FLTK_Point (double _x = 0.0, double _y = 0.0, Fl_Color _color = FL_BLACK, int _width = 0)
Constructeur.
Parameters:
_x abcisse du point (repère "monde").
_y ordonnée du point (repère "monde").
_color couleur du point.
_width taille du point.
Definition at line 61 of file graphic-objects.cc.
References x, and y.
Member Function Documentation
void FLTK_Point::draw (FLTK_Display * display) [virtual]
Implements FLTK_Graphic_Object.
Definition at line 66 of file graphic-objects.cc.
References FLTK_Graphic_Object::color, FLTK_Display::get_scroll_x(), FLTK_Display::get_scroll_y(), FLTK_Display::get_unit_size(), FLTK_Graphic_Object::style, FLTK_Graphic_Object::width, world_to_display_x(), world_to_display_y(), x, and y.
void FLTK_Point::print () [virtual]
Implements FLTK_Graphic_Object.
Definition at line 81 of file graphic-objects.cc.
References x, and y.
void FLTK_Point::xfigicize (ofstream & output) [virtual]
Implements FLTK_Graphic_Object.
Definition at line 85 of file graphic-objects.cc.
References FLTK_Graphic_Object::color, FLTK_Graphic_Object::style, FLTK_Graphic_Object::width, x, xfig_parametres(), xfig_x(), xfig_y(), and y.
Member Data Documentation
double FLTK_Point::x
Definition at line 79 of file graphic-objects.h.
Referenced by draw(), FLTK_Point(), print(), and xfigicize().
double FLTK_Point::y
Definition at line 79 of file graphic-objects.h.
Referenced by draw(), FLTK_Point(), print(), and xfigicize().
The documentation for this class was generated from the following files:
fltk-graphics/graphic-objects.h
fltk-graphics/graphic-objects.cc