CC Steer: FLTK_Line Class Reference
FLTK_Line Class Reference
#include <graphic-objects.h>
Public Member Functions
FLTK_Line (double _x1=0.0, double _y1=0.0, double _x2=0.0, double _y2=0.0, Fl_Color _color=FL_BLACK, int _style=FL_SOLID, int _width=0)
void draw (FLTK_Display *display)
void print ()
void xfigicize (ofstream &output)
Public Attributes
double x1
double y1
double x2
double y2
Detailed Description
Classe FLTK_Line: objet graphique de type ligne destiné à être affiché dans un widget FLTK_Display_control.
Definition at line 160 of file graphic-objects.h.
Constructor & Destructor Documentation
FLTK_Line::FLTK_Line (double _x1 = 0.0, double _y1 = 0.0, double _x2 = 0.0, double _y2 = 0.0, Fl_Color _color = FL_BLACK, int _style = FL_SOLID, int _width = 0)
Constructeur.
Parameters:
_x1 abcisse de l'extremité 1 (repère "monde").
_y1 ordonnée de l'extremité 1 (repère "monde").
_x2 abcisse de l'extremité 2 (repère "monde").
_y2 ordonnée de l'extremité 2 (repère "monde").
_color couleur du point.
_style style du point.
_width épaisseur du trait.
Definition at line 204 of file graphic-objects.cc.
References x1, x2, y1, and y2.
Member Function Documentation
void FLTK_Line::draw (FLTK_Display * display) [virtual]
Implements FLTK_Graphic_Object.
Definition at line 210 of file graphic-objects.cc.
References FLTK_Graphic_Object::color, FLTK_Display::get_scroll_x(), FLTK_Display::get_scroll_y(), FLTK_Display::get_unit_size(), FLTK_Graphic_Object::style, FLTK_Graphic_Object::width, world_to_display_x(), world_to_display_y(), x1, x2, y1, and y2.
void FLTK_Line::print () [virtual]
Implements FLTK_Graphic_Object.
Definition at line 227 of file graphic-objects.cc.
References x1, x2, y1, and y2.
void FLTK_Line::xfigicize (ofstream & output) [virtual]
Implements FLTK_Graphic_Object.
Definition at line 231 of file graphic-objects.cc.
References FLTK_Graphic_Object::color, FLTK_Graphic_Object::style, FLTK_Graphic_Object::width, x1, x2, xfig_parametres(), xfig_x(), xfig_y(), y1, and y2.
Member Data Documentation
double FLTK_Line::x1
Definition at line 163 of file graphic-objects.h.
Referenced by draw(), FLTK_Line(), print(), and xfigicize().
double FLTK_Line::y1
Definition at line 163 of file graphic-objects.h.
Referenced by draw(), FLTK_Line(), print(), and xfigicize().
double FLTK_Line::x2
Definition at line 163 of file graphic-objects.h.
Referenced by draw(), FLTK_Line(), print(), and xfigicize().
double FLTK_Line::y2
Definition at line 163 of file graphic-objects.h.
Referenced by draw(), FLTK_Line(), print(), and xfigicize().
The documentation for this class was generated from the following files:
fltk-graphics/graphic-objects.h
fltk-graphics/graphic-objects.cc