CC Steer: FLTK_Cross Class Reference
FLTK_Cross Class Reference
#include <graphic-objects.h>
Public Member Functions
FLTK_Cross (double _x=0.0, double _y=0.0, double _size=0.0, Fl_Color _color=FL_BLACK, int _style=FL_SOLID, int _width=0)
void draw (FLTK_Display *display)
void print ()
void xfigicize (ofstream &output)
Public Attributes
double x
double y
double size
Detailed Description
Classe FLTK_Cross: objet graphique de type croix destiné à être affiché dans un widget FLTK_Display_control.
Definition at line 102 of file graphic-objects.h.
Constructor & Destructor Documentation
FLTK_Cross::FLTK_Cross (double _x = 0.0, double _y = 0.0, double _size = 0.0, Fl_Color _color = FL_BLACK, int _style = FL_SOLID, int _width = 0)
Constructeur.
Parameters:
_x abcisse du centre de la croix (repère "monde").
_y ordonnée du centre de la croix (repère "monde").
_size longueur d'une demi-branche de la croix (repère "monde").
_color couleur du point.
_style style du tracé.
_width épaisseur du tracé.
Definition at line 100 of file graphic-objects.cc.
References size, x, and y.
Member Function Documentation
void FLTK_Cross::draw (FLTK_Display * display) [virtual]
Implements FLTK_Graphic_Object.
Definition at line 106 of file graphic-objects.cc.
References FLTK_Graphic_Object::color, FLTK_Display::get_scroll_x(), FLTK_Display::get_scroll_y(), FLTK_Display::get_unit_size(), size, FLTK_Graphic_Object::style, FLTK_Graphic_Object::width, world_to_display_x(), world_to_display_y(), x, and y.
void FLTK_Cross::print () [virtual]
Implements FLTK_Graphic_Object.
Definition at line 124 of file graphic-objects.cc.
References size, x, and y.
void FLTK_Cross::xfigicize (ofstream & output) [virtual]
Implements FLTK_Graphic_Object.
Definition at line 128 of file graphic-objects.cc.
References FLTK_Graphic_Object::color, size, FLTK_Graphic_Object::style, FLTK_Graphic_Object::width, x, xfig_parametres(), xfig_x(), xfig_y(), and y.
Member Data Documentation
double FLTK_Cross::x
Definition at line 105 of file graphic-objects.h.
Referenced by draw(), FLTK_Cross(), print(), and xfigicize().
double FLTK_Cross::y
Definition at line 105 of file graphic-objects.h.
Referenced by draw(), FLTK_Cross(), print(), and xfigicize().
double FLTK_Cross::size
Definition at line 105 of file graphic-objects.h.
Referenced by draw(), FLTK_Cross(), print(), and xfigicize().
The documentation for this class was generated from the following files:
fltk-graphics/graphic-objects.h
fltk-graphics/graphic-objects.cc