CC Steer: FLTK_Display_Control Class Reference
FLTK_Display_Control Class Reference
[FLTK_Display, FLTK_Display_Control et FLTK_Graphic_Object]
Fenêtre de contrôle d'un widget d'affichage graphique 2D.
#include <display.h>
Public Member Functions
FLTK_Display_Control (double _unit_size, double _scroll_x, double _scroll_y, int _w, int _h, char *_title)
void add_callback (void _callback(Fl_Widget *, void *))
void clear_objects ()
void add_object (FLTK_Graphic_Object *object)
void redraw ()
Public Attributes
Fl_Button quit
Fl_Button clear
Fl_Button xfig
Fl_Group zoom_group
Fl_Box zoom_title
Fl_Box zoom_value
Fl_Button zoom_reset
Fl_Button zoom_plus
Fl_Button zoom_minus
Fl_Group scroll_group
Fl_Box scroll_title
Fl_Box scroll_value_x
Fl_Box scroll_value_y
Fl_Button scroll_reset
Fl_Button scroll_up
Fl_Button scroll_down
Fl_Button scroll_left
Fl_Button scroll_right
FLTK_Display * display
Detailed Description
Fenêtre de contrôle d'un widget d'affichage graphique 2D.
Widget d'affichage graphique qui comporte deux fenêtres: une fenêtre de contrôle (objet de classe FLTK_Display_Control) et une fenêtre d'affichage 2D (objet de classe FLTK_Display). Est associée à ce widget une liste d'objets graphiques (objets de classe FLTK_Graphic_Object) qui sont representés dans la fenêtre d'affichage. La fenêtre de controle permet de gérer les paramètres de visualisation (échelle, point de vue), de réinitialiser la liste d'objets graphiques et de demander une sortie au format Xfig dans un fichier <nom du="" widget>="">-output.fig.
Definition at line 118 of file display.h.
Constructor & Destructor Documentation
FLTK_Display_Control::FLTK_Display_Control (double _unit_size, double _scroll_x, double _scroll_y, int _w, int _h, char * _title)
Constructeur. Crée la fenêtre de contrôle et la fenêtre d'affichage associée.
Parameters:
_unit_size taille (en pixels) de l'unité du repère "monde"
_scroll_x abcisse (en pixels) du repère "monde" par rapport au repère "fenêtre" (coin supérieur gauche de la fenêtre).
_scroll_y ordonnée (en pixels) du repère "monde" par rapport au repère "fenêtre" (coin supérieur gauche de la fenêtre).
_w largeur en pixels de la fenêtre.
_h hauteur en pixels de la fenêtre.
_title nom des fenêtres.
Definition at line 356 of file display.cc.
References cb_clear(), cb_quit(), cb_scroll_down(), cb_scroll_left(), cb_scroll_reset(), cb_scroll_right(), cb_scroll_up(), cb_xfig(), cb_zoom_minus(), cb_zoom_plus(), cb_zoom_reset(), clear, display, quit, scroll_down, scroll_group, scroll_left, scroll_reset, scroll_right, scroll_title, scroll_up, scroll_value_x, scroll_value_y, xfig, zoom_group, zoom_minus, zoom_plus, zoom_reset, zoom_title, and zoom_value.
Member Function Documentation
void FLTK_Display_Control::add_callback (void _callbackFl_Widget *, void *)
Ajout du callback associé a la fenêtre d'affichage,
Le callback est appelé lorsque que le curseur se trouve dans la fenêtre d'affichage et que l'un des boutons de la souris ou que l'une des touches du clavier est enfoncé.
Le callback est une fonction de type "void <callback> (Fl_Widget *display, void *data) {...}". Dans le callback, on peut déterminer quelle touche a été enfoncée à l'aide de la fonction "int *Flevent_key ();", ou quel bouton de la souris a été enfoncé à l'aide de la fonction "int Fl::event_button ();".
On peut récupérer la position en x de la souris (repère "monde") par "worldify_x (Fl::event_x (), (FLTK_Display *)display);" (idem pour la position en y: "worldify_y (Fl::event_y (), (FLTK_Display *)display);").
Definition at line 458 of file display.cc.
References display.
Referenced by main().
void FLTK_Display_Control::clear_objects ()
Réinitialisation de la liste des objets graphiques.
Attention, les objets graphiques (dont les pointeurs ont été passé à la fonction add_object) sont désalloués.
Definition at line 462 of file display.cc.
References FLTK_Display::clear_objects(), and display.
Referenced by main().
void FLTK_Display_Control::add_object (FLTK_Graphic_Object * object)
Ajout d'un objet graphique.
Parameters:
object pointeur sur l'objet FLTK_Graphic_Object à ajouter.
Definition at line 465 of file display.cc.
References FLTK_Display::add_object(), and display.
void FLTK_Display_Control::redraw ()
Rafraîchissement de l'affichage.
Definition at line 469 of file display.cc.
References display.
Member Data Documentation
Fl_Button FLTK_Display_Control::quit
Definition at line 121 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Button FLTK_Display_Control::clear
Definition at line 123 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Button FLTK_Display_Control::xfig
Definition at line 125 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Group FLTK_Display_Control::zoom_group
Definition at line 127 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Box FLTK_Display_Control::zoom_title
Definition at line 128 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Box FLTK_Display_Control::zoom_value
Definition at line 128 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Button FLTK_Display_Control::zoom_reset
Definition at line 129 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Button FLTK_Display_Control::zoom_plus
Definition at line 129 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Button FLTK_Display_Control::zoom_minus
Definition at line 129 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Group FLTK_Display_Control::scroll_group
Definition at line 131 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Box FLTK_Display_Control::scroll_title
Definition at line 132 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Box FLTK_Display_Control::scroll_value_x
Definition at line 132 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Box FLTK_Display_Control::scroll_value_y
Definition at line 132 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Button FLTK_Display_Control::scroll_reset
Definition at line 133 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Button FLTK_Display_Control::scroll_up
Definition at line 133 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Button FLTK_Display_Control::scroll_down
Definition at line 133 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Button FLTK_Display_Control::scroll_left
Definition at line 133 of file display.h.
Referenced by FLTK_Display_Control().
Fl_Button FLTK_Display_Control::scroll_right
Definition at line 133 of file display.h.
Referenced by FLTK_Display_Control().
FLTK_Display* FLTK_Display_Control::display
Definition at line 135 of file display.h.
Referenced by add_callback(), add_object(), clear_objects(), FLTK_Display_Control(), and redraw().
The documentation for this class was generated from the following files:
fltk-graphics/display.h
fltk-graphics/display.cc