CC Steer: FLTK_Display Class Reference
FLTK_Display Class Reference
[FLTK_Display, FLTK_Display_Control et FLTK_Graphic_Object]
Fenêtre d'affichage d'un widget d'affichage graphique 2D.
#include <display.h>
Public Member Functions
void draw ()
int handle (int e)
FLTK_Display (const double _unit_size, const double _scroll_x, const double _scroll_y, const int _w, const int _h, const char *_title)
~FLTK_Display ()
double get_init_unit_size () const
double get_init_scroll_x () const
double get_init_scroll_y () const
double get_unit_size () const
double get_scroll_x () const
double get_scroll_y () const
vector< FLTK_Graphic_Object * > get_list_objects () const
void set_unit_size (const double _unit_size)
void set_scroll_x (const double _scroll_x)
void set_scroll_y (const double _scroll_y)
void clear_objects ()
void add_object (FLTK_Graphic_Object *object)
Public Attributes
double init_unit_size
double unit_size
double init_scroll_x
double init_scroll_y
double scroll_x
double scroll_y
vector< FLTK_Graphic_Object * > list_objects
Friends
void cb_xfig (Fl_Widget *, void *data)
Detailed Description
Fenêtre d'affichage d'un widget d'affichage graphique 2D.
Widget d'affichage graphique qui comporte deux fenêtres: une fenêtre de contrôle (objet de classe FLTK_Display_Control) et une fenêtre d'affichage 2D (objet de classe FLTK_Display). Est associée à ce widget une liste d'objets graphiques (objets de classe FLTK_Graphic_Object) qui sont representés dans la fenêtre d'affichage. La fenêtre de controle permet de gérer les paramètres de visualisation (échelle, point de vue), de réinitialiser la liste d'objets graphiques et de demander une sortie au format Xfig dans un fichier <nom du="" widget>="">-output.fig.
Definition at line 60 of file display.h.
Constructor & Destructor Documentation
FLTK_Display::FLTK_Display (const double _unit_size, const double _scroll_x, const double _scroll_y, const int _w, const int _h, const char * _title)
Definition at line 17 of file display.cc.
References cb_empty_callback(), init_scroll_x, init_scroll_y, init_unit_size, scroll_x, scroll_y, and unit_size.
FLTK_Display::~FLTK_Display ()
Definition at line 41 of file display.cc.
References clear_objects().
Member Function Documentation
void FLTK_Display::draw ()
Definition at line 69 of file display.cc.
References get_scroll_x(), get_scroll_y(), get_unit_size(), list_objects, world_to_display_x(), and world_to_display_y().
int FLTK_Display::handle (int e)
Definition at line 110 of file display.cc.
double FLTK_Display::get_init_unit_size () const
Definition at line 47 of file display.cc.
References init_unit_size.
Referenced by cb_zoom_reset().
double FLTK_Display::get_init_scroll_x () const
Definition at line 48 of file display.cc.
References init_scroll_x.
Referenced by cb_scroll_reset().
double FLTK_Display::get_init_scroll_y () const
Definition at line 49 of file display.cc.
References init_scroll_y.
Referenced by cb_scroll_reset().
double FLTK_Display::get_unit_size () const
Definition at line 50 of file display.cc.
References unit_size.
Referenced by cb_dubins_rs(), cb_zoom_minus(), cb_zoom_plus(), FLTK_Clothoid::draw(), FLTK_Circle::draw(), FLTK_Arc::draw(), FLTK_Line::draw(), FLTK_Plus::draw(), FLTK_Cross::draw(), FLTK_Point::draw(), draw(), worldify_x(), and worldify_y().
double FLTK_Display::get_scroll_x () const
Definition at line 51 of file display.cc.
References scroll_x.
Referenced by cb_dubins_rs(), cb_scroll_left(), cb_scroll_right(), FLTK_Clothoid::draw(), FLTK_Circle::draw(), FLTK_Arc::draw(), FLTK_Line::draw(), FLTK_Plus::draw(), FLTK_Cross::draw(), FLTK_Point::draw(), draw(), and worldify_x().
double FLTK_Display::get_scroll_y () const
Definition at line 52 of file display.cc.
References scroll_y.
Referenced by cb_dubins_rs(), cb_scroll_down(), cb_scroll_up(), FLTK_Clothoid::draw(), FLTK_Circle::draw(), FLTK_Arc::draw(), FLTK_Line::draw(), FLTK_Plus::draw(), FLTK_Cross::draw(), FLTK_Point::draw(), draw(), and worldify_y().
vector< FLTK_Graphic_Object * > FLTK_Display::get_list_objects () const
Definition at line 53 of file display.cc.
References list_objects.
void FLTK_Display::set_unit_size (const double _unit_size)
Definition at line 57 of file display.cc.
References unit_size.
Referenced by cb_zoom_minus(), cb_zoom_plus(), and cb_zoom_reset().
void FLTK_Display::set_scroll_x (const double _scroll_x)
Definition at line 59 of file display.cc.
References scroll_x.
Referenced by cb_scroll_left(), cb_scroll_reset(), and cb_scroll_right().
void FLTK_Display::set_scroll_y (const double _scroll_y)
Definition at line 61 of file display.cc.
References scroll_y.
Referenced by cb_scroll_down(), cb_scroll_reset(), and cb_scroll_up().
void FLTK_Display::clear_objects ()
Definition at line 29 of file display.cc.
References list_objects.
Referenced by cb_clear(), cb_dubins_rs(), cb_empty(), FLTK_Display_Control::clear_objects(), and ~FLTK_Display().
void FLTK_Display::add_object (FLTK_Graphic_Object * object)
Definition at line 65 of file display.cc.
References list_objects.
Referenced by FLTK_Display_Control::add_object(), cc_turn_graphicize(), and graphicize().
Friends And Related Function Documentation
void cb_xfig (Fl_Widget * , void * data) [friend]
Definition at line 157 of file display.cc.
Member Data Documentation
double FLTK_Display::init_unit_size
Definition at line 63 of file display.h.
Referenced by FLTK_Display(), and get_init_unit_size().
double FLTK_Display::unit_size
Definition at line 65 of file display.h.
Referenced by cb_zoom_minus(), cb_zoom_plus(), cb_zoom_reset(), FLTK_Display(), get_unit_size(), and set_unit_size().
double FLTK_Display::init_scroll_x
Definition at line 68 of file display.h.
Referenced by FLTK_Display(), and get_init_scroll_x().
double FLTK_Display::init_scroll_y
Definition at line 68 of file display.h.
Referenced by FLTK_Display(), and get_init_scroll_y().
double FLTK_Display::scroll_x
Definition at line 71 of file display.h.
Referenced by cb_scroll_left(), cb_scroll_reset(), cb_scroll_right(), FLTK_Display(), get_scroll_x(), and set_scroll_x().
double FLTK_Display::scroll_y
Definition at line 71 of file display.h.
Referenced by cb_scroll_down(), cb_scroll_reset(), cb_scroll_up(), FLTK_Display(), get_scroll_y(), and set_scroll_y().
vector<FLTK_Graphic_Object *> FLTK_Display::list_objects
Definition at line 73 of file display.h.
Referenced by add_object(), cb_xfig(), clear_objects(), draw(), and get_list_objects().
The documentation for this class was generated from the following files:
fltk-graphics/display.h
fltk-graphics/display.cc