CC Steer: FLTK_Circle Class Reference
FLTK_Circle Class Reference
#include <graphic-objects.h>
Public Member Functions
FLTK_Circle (double _xc=0.0, double _yc=0.0, double _radius=0.0, Fl_Color _color=FL_BLACK, int _style=FL_SOLID, int _width=0)
void draw (FLTK_Display *display)
void print ()
void xfigicize (ofstream &output)
Public Attributes
double xc
double yc
double radius
Detailed Description
Classe FLTK_Circle: objet graphique de type cercle destiné à être affiché dans un widget FLTK_Display_control.
Definition at line 236 of file graphic-objects.h.
Constructor & Destructor Documentation
FLTK_Circle::FLTK_Circle (double _xc = 0.0, double _yc = 0.0, double _radius = 0.0, Fl_Color _color = FL_BLACK, int _style = FL_SOLID, int _width = 0)
Constructeur.
Parameters:
_xc abcisse du centre (repère "monde").
_yc ordonnée du centre (repère "monde").
_radius rayon du cercle (repère "monde").
_color couleur du point.
_style style du point.
_width épaisseur du trait.
Definition at line 359 of file graphic-objects.cc.
References radius, xc, and yc.
Member Function Documentation
void FLTK_Circle::draw (FLTK_Display * display) [virtual]
Implements FLTK_Graphic_Object.
Definition at line 367 of file graphic-objects.cc.
References FLTK_Graphic_Object::color, FLTK_Display::get_scroll_x(), FLTK_Display::get_scroll_y(), FLTK_Display::get_unit_size(), radius, FLTK_Graphic_Object::style, FLTK_Graphic_Object::width, world_to_display_x(), world_to_display_y(), xc, and yc.
void FLTK_Circle::print () [virtual]
Implements FLTK_Graphic_Object.
Definition at line 384 of file graphic-objects.cc.
References radius, xc, and yc.
void FLTK_Circle::xfigicize (ofstream & output) [virtual]
Implements FLTK_Graphic_Object.
Definition at line 388 of file graphic-objects.cc.
References FLTK_Graphic_Object::color, radius, FLTK_Graphic_Object::style, FLTK_Graphic_Object::width, xc, xfig_parametres(), xfig_x(), xfig_y(), and yc.
Member Data Documentation
double FLTK_Circle::xc
Definition at line 239 of file graphic-objects.h.
Referenced by draw(), FLTK_Circle(), print(), and xfigicize().
double FLTK_Circle::yc
Definition at line 239 of file graphic-objects.h.
Referenced by draw(), FLTK_Circle(), print(), and xfigicize().
double FLTK_Circle::radius
Definition at line 239 of file graphic-objects.h.
Referenced by draw(), FLTK_Circle(), print(), and xfigicize().
The documentation for this class was generated from the following files:
fltk-graphics/graphic-objects.h
fltk-graphics/graphic-objects.cc