CC Steer: smt/configuration.h File Reference
smt/configuration.h File Reference
#include <iostream>
#include <object.h>
#include <utilities.h>
Classes
class SMT_Configuration
Functions
double configuration_distance (SMT_Configuration q1, SMT_Configuration q2)
bool configuration_aligned (SMT_Configuration q1, SMT_Configuration q2)
bool configuration_equal (SMT_Configuration q1, SMT_Configuration q2)
Function Documentation
bool configuration_aligned (SMT_Configuration q1, SMT_Configuration q2)
Definition at line 44 of file configuration.cc.
References get_epsilon(), SMT_Configuration::theta, twopify(), SMT_Configuration::x, and SMT_Configuration::y.
Referenced by cc_circles_rs_path(), and cc_dubins().
double configuration_distance (SMT_Configuration q1, SMT_Configuration q2)
Definition at line 38 of file configuration.cc.
References point_distance(), SMT_Configuration::x, and SMT_Configuration::y.
Referenced by cc_circles_rs_path(), cc_dubins(), configuration_equal(), TceScT_path(), TceST_path(), TciScT_path(), TciST_path(), TeScT_path(), TeST_path(), TiScT_path(), and TiST_path().
bool configuration_equal (SMT_Configuration q1, SMT_Configuration q2)
Definition at line 54 of file configuration.cc.
References configuration_distance(), get_epsilon(), and SMT_Configuration::theta.
Referenced by cc_circles_rs_path(), and cc_dubins().