CC Steer: fltk-graphics/display.h File Reference
fltk-graphics/display.h File Reference
#include <iostream>
#include <fstream>
#include <vector>
#include <FL/Fl.H>
#include <FL/Fl_Widget.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Double_Window.H>
#include <FL/fl_draw.H>
#include <FL/Enumerations.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <utilities.h>
#include <graphic-objects.h>
Classes
class FLTK_Display
Fenêtre d'affichage d'un widget d'affichage graphique 2D.
class FLTK_Display_Control
Fenêtre de contrôle d'un widget d'affichage graphique 2D.
Functions
double worldify_x (int x, FLTK_Display *display)
double worldify_y (int y, FLTK_Display *display)
Function Documentation
double worldify_x (int x, FLTK_Display * display)
Fonction de conversion (abcisse) repère "fenêtre" -> repère "monde".
Definition at line 473 of file display.cc.
References display_to_world_x(), FLTK_Display::get_scroll_x(), and FLTK_Display::get_unit_size().
double worldify_y (int y, FLTK_Display * display)
Fonction de conversion (ordonnée) repère "fenêtre" -> repère "monde".
Definition at line 479 of file display.cc.
References display_to_world_y(), FLTK_Display::get_scroll_y(), and FLTK_Display::get_unit_size().