CC Steer: fltk-graphics/display.cc File Reference
fltk-graphics/display.cc File Reference
#include <display.h>
Functions
void cb_empty_callback (Fl_Widget *, void *)
void cb_quit (Fl_Widget *w, void *data)
void cb_clear (Fl_Widget *, void *data)
void cb_xfig (Fl_Widget *, void *data)
void cb_zoom_plus (Fl_Widget *w, void *data)
void cb_zoom_minus (Fl_Widget *w, void *data)
void cb_zoom_reset (Fl_Widget *w, void *data)
void cb_scroll_up (Fl_Widget *w, void *data)
void cb_scroll_down (Fl_Widget *w, void *data)
void cb_scroll_left (Fl_Widget *w, void *data)
void cb_scroll_right (Fl_Widget *w, void *data)
void cb_scroll_reset (Fl_Widget *w, void *data)
double worldify_x (int x, FLTK_Display *display)
double worldify_y (int y, FLTK_Display *display)
Function Documentation
void cb_clear (Fl_Widget * , void * data)
Definition at line 148 of file display.cc.
References FLTK_Display::clear_objects().
Referenced by FLTK_Display_Control::FLTK_Display_Control().
void cb_empty_callback (Fl_Widget * , void *)
Definition at line 14 of file display.cc.
Referenced by FLTK_Display::FLTK_Display().
void cb_quit (Fl_Widget * w, void * data)
Definition at line 140 of file display.cc.
Referenced by FLTK_Display_Control::FLTK_Display_Control().
void cb_scroll_down (Fl_Widget * w, void * data)
Definition at line 280 of file display.cc.
References FLTK_Display::get_scroll_y(), FLTK_Display::scroll_y, and FLTK_Display::set_scroll_y().
Referenced by FLTK_Display_Control::FLTK_Display_Control().
void cb_scroll_left (Fl_Widget * w, void * data)
Definition at line 298 of file display.cc.
References FLTK_Display::get_scroll_x(), FLTK_Display::scroll_x, and FLTK_Display::set_scroll_x().
Referenced by FLTK_Display_Control::FLTK_Display_Control().
void cb_scroll_reset (Fl_Widget * w, void * data)
Definition at line 334 of file display.cc.
References FLTK_Display::get_init_scroll_x(), FLTK_Display::get_init_scroll_y(), FLTK_Display::scroll_x, FLTK_Display::scroll_y, FLTK_Display::set_scroll_x(), and FLTK_Display::set_scroll_y().
Referenced by FLTK_Display_Control::FLTK_Display_Control().
void cb_scroll_right (Fl_Widget * w, void * data)
Definition at line 316 of file display.cc.
References FLTK_Display::get_scroll_x(), FLTK_Display::scroll_x, and FLTK_Display::set_scroll_x().
Referenced by FLTK_Display_Control::FLTK_Display_Control().
void cb_scroll_up (Fl_Widget * w, void * data)
Definition at line 262 of file display.cc.
References FLTK_Display::get_scroll_y(), FLTK_Display::scroll_y, and FLTK_Display::set_scroll_y().
Referenced by FLTK_Display_Control::FLTK_Display_Control().
void cb_xfig (Fl_Widget * , void * data)
Definition at line 157 of file display.cc.
References FLTK_Display::list_objects, xfig_x(), and xfig_y().
Referenced by FLTK_Display_Control::FLTK_Display_Control().
void cb_zoom_minus (Fl_Widget * w, void * data)
Definition at line 228 of file display.cc.
References FLTK_Display::get_unit_size(), FLTK_Display::set_unit_size(), and FLTK_Display::unit_size.
Referenced by FLTK_Display_Control::FLTK_Display_Control().
void cb_zoom_plus (Fl_Widget * w, void * data)
Definition at line 211 of file display.cc.
References FLTK_Display::get_unit_size(), FLTK_Display::set_unit_size(), and FLTK_Display::unit_size.
Referenced by FLTK_Display_Control::FLTK_Display_Control().
void cb_zoom_reset (Fl_Widget * w, void * data)
Definition at line 245 of file display.cc.
References FLTK_Display::get_init_unit_size(), FLTK_Display::set_unit_size(), and FLTK_Display::unit_size.
Referenced by FLTK_Display_Control::FLTK_Display_Control().
double worldify_x (int x, FLTK_Display * display)
Fonction de conversion (abcisse) repère "fenêtre" -> repère "monde".
Definition at line 473 of file display.cc.
References display_to_world_x(), FLTK_Display::get_scroll_x(), and FLTK_Display::get_unit_size().
double worldify_y (int y, FLTK_Display * display)
Fonction de conversion (ordonnée) repère "fenêtre" -> repère "monde".
Definition at line 479 of file display.cc.
References display_to_world_y(), FLTK_Display::get_scroll_y(), and FLTK_Display::get_unit_size().