CC Steer: fltk-graphics/graphic-objects.h File Reference
fltk-graphics/graphic-objects.h File Reference
#include <iostream>
#include <fstream>
#include <vector>
#include <math.h>
#include <FL/Fl.H>
#include <FL/Enumerations.H>
#include <FL/fl_draw.H>
#include <utilities.h>
#include <display.h>
Classes
class FLTK_Graphic_Object
Objet graphique générique destiné à être affiché dans un widget d'affichage graphique 2D.
class FLTK_Point
class FLTK_Cross
class FLTK_Plus
class FLTK_Line
class FLTK_Arc
class FLTK_Circle
class FLTK_Clothoid
Functions
int xfig_x (double x)
int xfig_y (double y)
Function Documentation
int xfig_x (double x)
Definition at line 44 of file graphic-objects.cc.
Referenced by cb_xfig(), FLTK_Clothoid::xfigicize(), FLTK_Circle::xfigicize(), FLTK_Arc::xfigicize(), FLTK_Line::xfigicize(), FLTK_Plus::xfigicize(), FLTK_Cross::xfigicize(), and FLTK_Point::xfigicize().
int xfig_y (double y)
Definition at line 45 of file graphic-objects.cc.
Referenced by cb_xfig(), FLTK_Clothoid::xfigicize(), FLTK_Circle::xfigicize(), FLTK_Arc::xfigicize(), FLTK_Line::xfigicize(), FLTK_Plus::xfigicize(), FLTK_Cross::xfigicize(), and FLTK_Point::xfigicize().