CC Steer: smt/graphicize.h File Reference
smt/graphicize.h File Reference
#include <iostream>
#include <utilities.h>
#include <configuration.h>
#include <paths.h>
#include <display.h>
Functions
void set_cross_size (double size)
void set_clothoid_step (double step)
void cc_turn_graphicize (SMT_CC_Circle c, SMT_Configuration q, bool cusps, FLTK_Display *display, Fl_Color color, int style, int width)
void graphicize (SMT_Configuration q, FLTK_Display *display, Fl_Color color=FL_BLACK, int style=FL_SOLID, int width=0)
void graphicize (SMT_CC_Circle c, FLTK_Display *display, Fl_Color color=FL_BLACK, int style=FL_SOLID, int width=0)
void graphicize (SMT_CC_Dubins_Path p, FLTK_Display *display, Fl_Color color=FL_BLACK, int style=FL_SOLID, int width=0)
void graphicize (SMT_CC_RS_Path p, FLTK_Display *display, Fl_Color color=FL_BLACK, int style=FL_SOLID, int width=0)
Function Documentation
void cc_turn_graphicize (SMT_CC_Circle c, SMT_Configuration q, bool cusps, FLTK_Display * display, Fl_Color color, int style, int width)
Definition at line 27 of file graphicize.cc.
References Clothoid_Step, D1(), end_of_clothoid(), SMT_CC_Circle::first, SMT_CC_Circle::forward, get_epsilon(), SMT_Configuration::kappa, SMT_CC_Circle::kappa, SMT_CC_Circle::left, Pi, point_distance(), SMT_CC_Circle::sigma, SMT_CC_Circle::start, SMT_Configuration::theta, twopify(), SMT_Configuration::x, SMT_CC_Circle::xc, SMT_Configuration::y, and SMT_CC_Circle::yc.
Referenced by graphicize().
void graphicize (SMT_CC_RS_Path p, FLTK_Display * display, Fl_Color color = FL_BLACK, int style = FL_SOLID, int width = 0)
Definition at line 229 of file graphicize.cc.
References cc_turn_graphicize(), SMT_CC_RS_Path::cend, SMT_CC_RS_Path::ci1, SMT_CC_RS_Path::cstart, Empty, SMT_CC_RS_Path::end, graphicize(), null(), SMT_CC_RS_Path::qi1, SMT_CC_RS_Path::qi2, SMT_CC_RS_Path::qi3, SMT_CC_RS_Path::qi4, Segment, SMT_CC_RS_Path::start, T, TcScT, TcST, TcT, TcTcT, TcTT, TScT, TST, TT, TTcT, TTT, SMT_CC_RS_Path::type, SMT_Configuration::x, and SMT_Configuration::y.
void graphicize (SMT_CC_Dubins_Path p, FLTK_Display * display, Fl_Color color = FL_BLACK, int style = FL_SOLID, int width = 0)
Definition at line 164 of file graphicize.cc.
References cc_turn_graphicize(), SMT_CC_Dubins_Path::cend, SMT_CC_Dubins_Path::ci1, SMT_CC_Dubins_Path::cstart, EMPTY, SMT_CC_Dubins_Path::end, graphicize(), L, LR1L, LR2L, LS, LSL, LSR, null(), SMT_CC_Dubins_Path::qi1, SMT_CC_Dubins_Path::qi2, R, RL1R, RL2R, RS, RSL, RSR, S, SL, SR, SMT_CC_Dubins_Path::start, SMT_CC_Dubins_Path::type, SMT_Configuration::x, and SMT_Configuration::y.
void graphicize (SMT_CC_Circle c, FLTK_Display * display, Fl_Color color = FL_BLACK, int style = FL_SOLID, int width = 0)
Definition at line 139 of file graphicize.cc.
References Clothoid_Step, SMT_CC_Circle::first, SMT_CC_Circle::forward, graphicize(), SMT_CC_Circle::kappa, SMT_Configuration::kappa, SMT_CC_Circle::radius, SMT_CC_Circle::sigma, SMT_CC_Circle::start, SMT_Configuration::theta, SMT_Configuration::x, SMT_CC_Circle::xc, SMT_Configuration::y, and SMT_CC_Circle::yc.
void graphicize (SMT_Configuration q, FLTK_Display * display, Fl_Color color = FL_BLACK, int style = FL_SOLID, int width = 0)
Definition at line 124 of file graphicize.cc.
References SMT_Configuration::theta, SMT_Configuration::x, and SMT_Configuration::y.
Referenced by cb_dubins_rs(), cb_empty(), and graphicize().
void set_clothoid_step (double step)
Definition at line 21 of file graphicize.cc.
References Clothoid_Step.
void set_cross_size (double size)
Definition at line 13 of file graphicize.cc.
References Cross_Size.