CC Steer: smt/paths.h File Reference
smt/paths.h File Reference
#include <iostream>
#include <math.h>
#include <object.h>
#include <configuration.h>
#include <utilities.h>
Classes
class SMT_CC_Circle
class SMT_Path
class SMT_CC_Dubins_Path
class SMT_CC_RS_Path
class SMT_SC_Path
class SMT_CC_TP_Path
Enumerations
enum cc_dubins_path_type {
LSL, LSR, RSL, RSR,
LR1L, LR2L, RL1R, RL2R,
S, L, R, LS,
SL, SR, RS, EMPTY
}
enum cc_rs_path_type {
Empty, Segment, T, TT,
TcT, TST, TcST, TScT,
TcScT, TTT, TcTT, TTcT,
TcTcT, TTST, TcTST, TTcST,
TTScT, TcTcST, TcTScT, TTcScT,
TcTcScT, TTSTT, TcTSTT, TTcSTT,
TTScTT, TTSTcT, TcTcSTT, TTcScTT,
TTScTcT, TcTScTT, TcTSTcT, TTcSTcT,
TcTcScTT, TcTcSTcT, TcTScTcT, TTcScTcT,
TcTcScTcT
}
Functions
bool external_mu_tangent_exists (SMT_CC_Circle c1, SMT_CC_Circle c2)
void external_mu_tangent (SMT_CC_Circle c1, SMT_CC_Circle c2, SMT_Configuration **q1, SMT_Configuration **q2)
bool internal_mu_tangent_exists (SMT_CC_Circle c1, SMT_CC_Circle c2)
void internal_mu_tangent (SMT_CC_Circle c1, SMT_CC_Circle c2, SMT_Configuration **q1, SMT_Configuration **q2)
bool tangent_circle_exists (SMT_CC_Circle c1, SMT_CC_Circle c2)
void tangent_circle (SMT_CC_Circle c1, SMT_CC_Circle c2, SMT_Configuration **q1, SMT_Configuration **q2, SMT_Configuration **q3, SMT_Configuration **q4)
double cc_turn_length (SMT_CC_Circle *c, SMT_Configuration *q, bool cusps)
double rs_turn_length (SMT_CC_Circle *c, SMT_Configuration *q)
double dubins_turn_length (SMT_CC_Circle *c, SMT_Configuration *q)
void deflection_to_configuration (SMT_CC_Circle c, double deflection, SMT_Configuration *q)
bool configuration_on_cc_circle (SMT_CC_Circle c, SMT_Configuration q)
Variables
const int nb_cc_dubins_paths = 16
const int nb_cc_rs_paths = 37
Enumeration Type Documentation
enum cc_dubins_path_type
Enumerator:
LSL
LSR
RSL
RSR
LR1L
LR2L
RL1R
RL2R
S
L
R
LS
SL
SR
RS
EMPTY
Definition at line 73 of file paths.h.
enum cc_rs_path_type
Enumerator:
Empty
Segment
T
TT
TcT
TST
TcST
TScT
TcScT
TTT
TcTT
TTcT
TcTcT
TTST
TcTST
TTcST
TTScT
TcTcST
TcTScT
TTcScT
TcTcScT
TTSTT
TcTSTT
TTcSTT
TTScTT
TTSTcT
TcTcSTT
TTcScTT
TTScTcT
TcTScTT
TcTSTcT
TTcSTcT
TcTcScTT
TcTcSTcT
TcTScTcT
TTcScTcT
TcTcScTcT
Definition at line 113 of file paths.h.
Function Documentation
double cc_turn_length (SMT_CC_Circle * c, SMT_Configuration * q, bool cusps)
Definition at line 424 of file paths.cc.
References D1(), SMT_CC_Circle::forward, get_epsilon(), SMT_CC_Circle::kappa, SMT_CC_Circle::left, SMT_CC_Circle::mu, Pi, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::sigma, SMT_CC_Circle::start, SMT_Configuration::theta, Two_Pi, twopify(), SMT_Configuration::x, and SMT_Configuration::y.
Referenced by dubins_turn_length(), and rs_turn_length().
bool configuration_on_cc_circle (SMT_CC_Circle c, SMT_Configuration q)
Definition at line 504 of file paths.cc.
References SMT_CC_Circle::forward, get_epsilon(), Half_Pi, SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_Configuration::theta, twopify(), SMT_Configuration::x, SMT_CC_Circle::xc, SMT_Configuration::y, and SMT_CC_Circle::yc.
Referenced by cc_circles_rs_path(), and cc_dubins().
void deflection_to_configuration (SMT_CC_Circle c, double deflection, SMT_Configuration * q)
Definition at line 479 of file paths.cc.
References SMT_CC_Circle::forward, global_frame_change(), SMT_Configuration::kappa, SMT_CC_Circle::left, SMT_CC_Circle::mu, SMT_CC_Circle::radius, SMT_CC_Circle::start, SMT_Configuration::theta, twopify(), SMT_Configuration::x, and SMT_Configuration::y.
double dubins_turn_length (SMT_CC_Circle * c, SMT_Configuration * q)
Definition at line 473 of file paths.cc.
References cc_turn_length().
Referenced by cc_dubins().
void external_mu_tangent (SMT_CC_Circle c1, SMT_CC_Circle c2, SMT_Configuration ** q1, SMT_Configuration ** q2)
Definition at line 267 of file paths.cc.
References SMT_CC_Circle::forward, global_frame_change(), SMT_CC_Circle::left, SMT_CC_Circle::mu, SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by cc_dubins().
bool external_mu_tangent_exists (SMT_CC_Circle c1, SMT_CC_Circle c2)
Definition at line 253 of file paths.cc.
References SMT_CC_Circle::forward, get_epsilon(), SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by cc_dubins().
void internal_mu_tangent (SMT_CC_Circle c1, SMT_CC_Circle c2, SMT_Configuration ** q1, SMT_Configuration ** q2)
Definition at line 305 of file paths.cc.
References SMT_CC_Circle::forward, global_frame_change(), SMT_CC_Circle::left, SMT_CC_Circle::mu, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by cc_dubins().
bool internal_mu_tangent_exists (SMT_CC_Circle c1, SMT_CC_Circle c2)
Definition at line 294 of file paths.cc.
References SMT_CC_Circle::forward, SMT_CC_Circle::left, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by cc_dubins().
double rs_turn_length (SMT_CC_Circle * c, SMT_Configuration * q)
Definition at line 466 of file paths.cc.
References cc_turn_length().
Referenced by cc_circles_rs_path(), TceScT_path(), TceST_path(), TciScT_path(), TciST_path(), TcT_path(), TcTcT_path(), TcTT_path(), TeScT_path(), TeST_path(), TiScT_path(), TiST_path(), TT_path(), TTcT_path(), and TTT_path().
void tangent_circle (SMT_CC_Circle c1, SMT_CC_Circle c2, SMT_Configuration ** q1, SMT_Configuration ** q2, SMT_Configuration ** q3, SMT_Configuration ** q4)
Definition at line 349 of file paths.cc.
References SMT_CC_Circle::forward, global_frame_change(), Half_Pi, SMT_CC_Circle::left, SMT_CC_Circle::mu, Pi, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by cc_dubins().
bool tangent_circle_exists (SMT_CC_Circle c1, SMT_CC_Circle c2)
Definition at line 338 of file paths.cc.
References SMT_CC_Circle::forward, SMT_CC_Circle::left, point_distance(), SMT_CC_Circle::radius, SMT_CC_Circle::xc, and SMT_CC_Circle::yc.
Referenced by cc_dubins().
Variable Documentation
const int nb_cc_dubins_paths = 16
Definition at line 76 of file paths.h.
Referenced by cc_dubins().
const int nb_cc_rs_paths = 37
Definition at line 123 of file paths.h.
Referenced by cc_circles_rs_path().