CC Steer: main/test-nw.cc File Reference
main/test-nw.cc File Reference
#include <iostream>
#include <fstream>
#include <utilities.h>
#include <configuration.h>
#include <paths.h>
#include <cc-dubins.h>
#include <cc-rs.h>
Functions
int main (int argc, char **argv)
Variables
double KappaMax = 1.0
double SigmaMax = 1.0
SMT_Configuration start (0, 0, 0, 0)
SMT_Configuration goal (1, 1, 0.785, 0)
Function Documentation
int main (int argc, char ** argv)
Definition at line 28 of file test-nw.cc.
References cc_dubins(), cc_reeds_shepp(), goal, SMT_Configuration::kappa, KappaMax, SMT_CC_RS_Path::print(), SMT_CC_Dubins_Path::print(), SigmaMax, start, SMT_Configuration::theta, SMT_Configuration::x, and SMT_Configuration::y.
Variable Documentation
SMT_Configuration goal(1, 1, 0.785, 0)
Referenced by cb_dubins_rs(), cb_empty(), and main().
double KappaMax = 1.0
Definition at line 18 of file test-nw.cc.
Referenced by cb_dubins_rs(), and main().
double SigmaMax = 1.0
Definition at line 19 of file test-nw.cc.
Referenced by cb_dubins_rs(), and main().
SMT_Configuration start(0, 0, 0, 0)
Referenced by cb_dubins_rs(), cb_empty(), and main().