CC Steer: main/test.cc File Reference
main/test.cc File Reference
#include <iostream>
#include <fstream>
#include <display.h>
#include <graphicize.h>
#include <utilities.h>
#include <configuration.h>
#include <paths.h>
#include <cc-dubins.h>
#include <cc-rs.h>
Functions
FLTK_Display_Control control (100, 250,-250, 500, 500, window_title)
void cb_dubins_rs (Fl_Widget *w, void *data)
void cb_empty (Fl_Widget *w, void *data)
int main (int argc, char **argv)
Variables
double KappaMax = 1.0
double SigmaMax = 1.0
SMT_Configuration start (1, 1, 0, 0)
SMT_Configuration goal (0, 0, 0.785, 0)
bool graphic_trace = false
char * window_title = strdup("SMT")
Function Documentation
void cb_dubins_rs (Fl_Widget * w, void * data)
Definition at line 35 of file test.cc.
References cc_dubins(), cc_reeds_shepp(), display_to_world_x(), display_to_world_y(), goal, graphic_trace, graphicize(), KappaMax, SMT_CC_RS_Path::print(), SMT_CC_Dubins_Path::print(), SigmaMax, start, SMT_Configuration::x, and SMT_Configuration::y.
void cb_empty (Fl_Widget * w, void * data)
Definition at line 76 of file test.cc.
References goal, graphic_trace, graphicize(), and start.
Referenced by main().
FLTK_Display_Control control (100 , 250 , - 250, 500 , 500 , window_title)
Referenced by main().
int main (int argc, char ** argv)
Definition at line 91 of file test.cc.
References cb_empty(), and control().
Variable Documentation
SMT_Configuration goal(0, 0, 0.785, 0)
bool graphic_trace = false
Definition at line 29 of file test.cc.
Referenced by cb_dubins_rs(), and cb_empty().
double KappaMax = 1.0
Definition at line 20 of file test.cc.
double SigmaMax = 1.0
Definition at line 21 of file test.cc.
SMT_Configuration start(1, 1, 0, 0)
char* window_title = strdup("SMT")
Definition at line 31 of file test.cc.