CC Steer: utilities/utilities.cc File Reference
utilities/utilities.cc File Reference
#include <utilities.h>
#include <fresnel.data>
Functions
void set_epsilon (double epsilon)
set epsilon's value (for numerical approximation).
double get_epsilon ()
get epsilon's value (for numerical approximation).
double elapsed_time (timeval begin, timeval end)
void start_chronometer ()
start chronometer.
double look_at_chronometer ()
get elasped time (in microseconds) since the chronometer was last started.
double point_distance (double x1, double y1, double x2, double y2)
cartesian distance between two points.
double world_to_display_x (double x, double unit_size, double scroll_x)
conversions repere "monde" <-> repere "display".
double world_to_display_y (double y, double unit_size, double scroll_y)
double display_to_world_x (double x, double unit_size, double scroll_x)
double display_to_world_y (double y, double unit_size, double scroll_y)
double twopify (double alpha)
conversion angle quelconque -> angle dans l'intervalle [0, 2pi[ radians
double degrees (double alpha)
conversion radians <-> degres
double radians (double alpha)
double fresnel (double x, bool fresnelc)
double fresnelc (double s)
integrales de fresnel
double fresnels (double s)
void end_of_clothoid (double x_i, double y_i, double theta_i, double kappa_i, double sigma, bool forward, double length, double *x_f, double *y_f, double *theta_f, double *kappa_f)
void end_of_circular_arc (double x_i, double y_i, double theta_i, double kappa, bool forward, double length, double *x_f, double *y_f, double *theta_f)
void global_frame_change (double x, double y, double theta, double local_x, double local_y, double *global_x, double *global_y)
void local_frame_change (double x, double y, double theta, double global_x, double global_y, double *local_x, double *local_y)
void plot_function (double(*f)(double), double min, double max, double step, char *filename)
double D1 (double alpha)
calul de la fonction D1 pour un angle alpha compris entre 0 et pi
bool null (void *p)
test de la nullite d'un pointeur (p == 0 ?)
int array_index_min (double array[], int size)
determination de l'index du plus petit element d'un tableau de double
void double_array_init (double array[], int size, double value)
initialisation a une valeur donnee d'un tableau de double
void pointer_array_init (void *array[], int size)
initialisation a NIL d'un tableau de pointeurs
void random_init ()
initialisation du generateur de nombres aleatoires
double random_real (double r)
generation d'un reel aleatoire compris entre 0 et r
double random_real (double r1, double r2)
generation d'un reel aleatoire compris entre r1 et r2
Variables
double Epsilon = 0.001
struct timeval time_begin time_end
struct timezone time_zone
Function Documentation
int array_index_min (double array[], int size)
determination de l'index du plus petit element d'un tableau de double
Definition at line 208 of file utilities.cc.
Referenced by cc_circles_rs_path(), cc_dubins(), and cc_reeds_shepp().
double D1 (double alpha)
calul de la fonction D1 pour un angle alpha compris entre 0 et pi
Definition at line 200 of file utilities.cc.
References fresnelc(), fresnels(), and Pi.
Referenced by cc_turn_graphicize(), and cc_turn_length().
double degrees (double alpha)
conversion radians <-> degres
Definition at line 61 of file utilities.cc.
References Pi.
Referenced by SMT_CC_Circle::print(), and SMT_Configuration::print().
double display_to_world_x (double x, double unit_size, double scroll_x)
Definition at line 48 of file utilities.cc.
Referenced by cb_dubins_rs().
double display_to_world_y (double y, double unit_size, double scroll_y)
Definition at line 51 of file utilities.cc.
Referenced by cb_dubins_rs().
void double_array_init (double array[], int size, double value)
initialisation a une valeur donnee d'un tableau de double
Definition at line 217 of file utilities.cc.
Referenced by cc_circles_rs_path(), and cc_dubins().
double elapsed_time (timeval begin, timeval end)
Definition at line 23 of file utilities.cc.
Referenced by look_at_chronometer().
void end_of_circular_arc (double x_i, double y_i, double theta_i, double kappa, bool forward, double length, double * x_f, double * y_f, double * theta_f)
calcul de l'extremite d'un arc de cercle x_i, y_i, theta_i: configuration initiale kappa: courbure du cercle (signee) forward: marche avant, marche arriere ? length: longueur de l'arc de cercle (positive) resultat retourne dans x_f, y_f, theta_f
Definition at line 141 of file utilities.cc.
References Epsilon, and twopify().
void end_of_clothoid (double x_i, double y_i, double theta_i, double kappa_i, double sigma, bool forward, double length, double * x_f, double * y_f, double * theta_f, double * kappa_f)
calcul de l'extremite d'un arc de clotoide x_i, y_i, theta_i, kappa_i: configuration initiale sigma: "sharpness" de la clotoide (signee) forward: marche avant, marche arriere ? length: longueur de l'arc de clotoide (positive) resultat retourne dans x_f, y_f, theta_f, kappa_f
Definition at line 84 of file utilities.cc.
References Epsilon, fresnelc(), fresnels(), global_frame_change(), Pi, sgn, and twopify().
Referenced by cc_turn_graphicize(), and SMT_CC_Circle::SMT_CC_Circle().
double fresnel (double x, bool fresnelc)
Definition at line 65 of file utilities.cc.
References sgn.
Referenced by fresnelc(), and fresnels().
double fresnelc (double s)
integrales de fresnel
Definition at line 79 of file utilities.cc.
References fresnel().
Referenced by D1(), and end_of_clothoid().
double fresnels (double s)
Definition at line 81 of file utilities.cc.
References fresnel().
Referenced by D1(), and end_of_clothoid().
double get_epsilon ()
get epsilon's value (for numerical approximation).
Definition at line 14 of file utilities.cc.
References Epsilon.
Referenced by cc_turn_graphicize(), cc_turn_length(), configuration_aligned(), configuration_equal(), configuration_on_cc_circle(), external_mu_tangent_exists(), TceScT_exists(), TceST_exists(), TcT_exists(), TeScT_exists(), TT_exists(), TTeSTT_exists(), and TTiSTT_exists().
void global_frame_change (double x, double y, double theta, double local_x, double local_y, double * global_x, double * global_y)
changement de repere: soit un repere local defini par son origine (x, y) et son orientation theta dans un repere global. soit (local_x, local_y) les coordonnees d'un point dans le repere local, la fonction retourne (global_x, global_y) les coordonnees de ce point dans le repere global.
Definition at line 167 of file utilities.cc.
Referenced by deflection_to_configuration(), end_of_clothoid(), external_mu_tangent(), internal_mu_tangent(), tangent_circle(), TceScT_path(), TceST_path(), TciScT_path(), TciST_path(), TcT_path(), TcTcT_tangent_circles(), TcTT_tangent_circles(), TeScT_path(), TeST_path(), TiScT_path(), TiST_path(), TTcT_tangent_circles(), and TTT_tangent_circles().
void local_frame_change (double x, double y, double theta, double global_x, double global_y, double * local_x, double * local_y)
changement de repere: soit un repere local defini par son origine (x, y) et son orientation theta dans un repere global. soit (global_x, global_y) les coordonnees d'un point dans le repere global, la fonction retourne (local_x, local_y) les coordonnees de ce point dans le repere local.
Definition at line 177 of file utilities.cc.
double look_at_chronometer ()
get elasped time (in microseconds) since the chronometer was last started.
Definition at line 32 of file utilities.cc.
References elapsed_time(), time_end, and time_zone.
Referenced by cc_dubins(), and cc_reeds_shepp().
bool null (void * p)
test de la nullite d'un pointeur (p == 0 ?)
Definition at line 205 of file utilities.cc.
Referenced by cc_reeds_shepp(), graphicize(), SMT_CC_TP_Path::print(), SMT_CC_RS_Path::print(), and SMT_CC_Dubins_Path::print().
void plot_function (double(*)(double) f, double min, double max, double step, char * filename)
"plot" d'une fonction f dans un fichier destine a gnuplot. f est de type "double f (double x)", on plot f de min a max avec le pas d'echantillonnage step dans le fichier filename.
Definition at line 186 of file utilities.cc.
double point_distance (double x1, double y1, double x2, double y2)
cartesian distance between two points.
Definition at line 38 of file utilities.cc.
Referenced by cc_turn_graphicize(), cc_turn_length(), configuration_distance(), configuration_on_cc_circle(), external_mu_tangent_exists(), internal_mu_tangent(), internal_mu_tangent_exists(), SMT_CC_Circle::SMT_CC_Circle(), tangent_circle(), tangent_circle_exists(), TceScT_exists(), TceST_exists(), TciScT_exists(), TciScT_path(), TciST_exists(), TciST_path(), TcT_exists(), TcT_path(), TcTcT_exists(), TcTcT_tangent_circles(), TcTT_exists(), TcTT_tangent_circles(), TeScT_exists(), TeST_exists(), TiScT_exists(), TiScT_path(), TiST_exists(), TiST_path(), TT_exists(), TTcT_exists(), TTcT_tangent_circles(), TTeSTT_exists(), TTiSTT_exists(), TTT_exists(), and TTT_tangent_circles().
void pointer_array_init (void * array[], int size)
initialisation a NIL d'un tableau de pointeurs
Definition at line 222 of file utilities.cc.
Referenced by cc_circles_rs_path(), and cc_dubins().
double radians (double alpha)
Definition at line 62 of file utilities.cc.
References Pi.
void random_init ()
initialisation du generateur de nombres aleatoires
Definition at line 227 of file utilities.cc.
double random_real (double r1, double r2)
generation d'un reel aleatoire compris entre r1 et r2
Definition at line 241 of file utilities.cc.
double random_real (double r)
generation d'un reel aleatoire compris entre 0 et r
Definition at line 235 of file utilities.cc.
void set_epsilon (double epsilon)
set epsilon's value (for numerical approximation).
Definition at line 13 of file utilities.cc.
References Epsilon.
void start_chronometer ()
start chronometer.
Definition at line 27 of file utilities.cc.
References time_zone.
Referenced by cc_dubins(), and cc_reeds_shepp().
double twopify (double alpha)
conversion angle quelconque -> angle dans l'intervalle [0, 2pi[ radians
Definition at line 55 of file utilities.cc.
References Pi, and Two_Pi.
Referenced by cc_turn_graphicize(), cc_turn_length(), configuration_aligned(), configuration_on_cc_circle(), deflection_to_configuration(), end_of_circular_arc(), end_of_clothoid(), and SMT_Configuration::SMT_Configuration().
double world_to_display_x (double x, double unit_size, double scroll_x)
conversions repere "monde" <-> repere "display".
conversions repere "monde" <-> repere "display". une unite est representee par unit_size pixels. le repere "monde" se trouve a la position (scroll_x, scroll_y) par rapport au repere "display".
Definition at line 42 of file utilities.cc.
double world_to_display_y (double y, double unit_size, double scroll_y)
Definition at line 45 of file utilities.cc.
Variable Documentation
double Epsilon = 0.001
Definition at line 10 of file utilities.cc.
Referenced by end_of_circular_arc(), end_of_clothoid(), get_epsilon(), and set_epsilon().
struct timeval time_begin time_end
Definition at line 19 of file utilities.cc.
Referenced by look_at_chronometer().
struct timezone time_zone
Definition at line 20 of file utilities.cc.
Referenced by look_at_chronometer(), and start_chronometer().